




.build/leonardo/src/sketch.cpp : src/sketch.ino
	@mkdir -p .build/leonardo/src
	@echo [93msrc/sketch.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/leonardo/src/sketch.cpp
	@true

