







	



.build/leonardo/NewPing/NewPing.d : lib/NewPing/NewPing.cpp
	@mkdir -p .build/leonardo/NewPing
	@/usr/bin/avr-gcc -mmcu=atmega32u4 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/NewPing -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/Firmata  -MM $^ > $@
	
	@printf ".build/leonardo/NewPing/NewPing.d .build/leonardo/NewPing/" | cat - $@ > $@~ && mv $@~ $@



.build/leonardo/NewPing/dependencies.d : .build/leonardo/NewPing/NewPing.d
	@echo [96mScanning dependencies of NewPing[0m
	@mkdir -p .build/leonardo/NewPing
	@cat $^ > $@;

all : .build/leonardo/NewPing/dependencies.d
	@true

